### ISSUE TITLE
How does your I3Kornhe work?

### ISSUE THREAD

**Issue by Flores02** [budRich/dots#1]
Hello BudRich,
First of all I would like to thank you for all your work on i3 ricing.
I was taking a look at your dots files and got stuck on your i3config about i3Kornhe, the tool you use to resize and move windows.

You have only these 4 key bindings to enter the modes, no modes definition and no mode-related keybindings like you show in the README of i3Kornhe.

I would like to know how is it possible and how do you make your i3Kornhe work with that structure?

**Comment by budRich** [comment]
I think that config file is old and uses the old i3Kornhe (that was located in budlabs/i3add), i have now moved i3Kornhe to i3ass and made a big update on it, see the readme file for i3Kornhe:  
https://github.com/budlabs/i3ass/tree/master/i3Kornhe

Thanks for reminding me, that I should update my dots. I think i will do that today.

Happy tiling! budRich

**Comment by Flores02** [comment]
Oh alright, thank you very much for this quick answer. 
I'm impatient to see your new dots files haha.
Have a nice day :)
